# Generated by Django 4.0.4 on 2023-05-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default='this is nigeria'),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.TextField(default='this is nigeria'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='this is nigeria'),
        ),
    ]
