# Generated by Django 4.0.4 on 2023-05-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='this is nigeria', upload_to='static/images/'),
        ),
    ]
