# Generated by Django 4.0.4 on 2023-06-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='this is nigeria', max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='static/images/')),
            ],
        ),
    ]
