# Generated by Django 4.0.4 on 2023-06-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='title',
            new_name='name',
        ),
    ]
