# Generated by Django 4.0.4 on 2023-06-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_rename_title_certificate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/pdfs/'),
        ),
    ]
